server:
  port: 8081  # Loans service ke liye aap yahan 8090 ya koi aur port rakh sakte hain

spring:
  application:
    name: accounts-service  # Loans service ke liye 'loans-service' likhein

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/